FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /redirector ./cmd/redirector

FROM alpine:3.20
COPY --from=build /redirector /redirector
EXPOSE 8081
ENTRYPOINT ["/redirector"]